version: "3"

services:
  d_one_backend:
    container_name: backendcontainer
    hostname: backendcontainer
    # underscore(_) can't be used for domain name
    build:
      context: ./dev_d_one/api_d_one
      dockerfile: ./Dockerfile
      args:
        REACT_SERVICE_HOST: $REACT_SERVICE_HOST
    ports:
      - "8000:8000"
    environment:
      - ALLOWED_HOSTS=* #d_one_backend,localhost,127.0.0.1,d_one_frontend,nginx
      - BACKEND_ENDPOINT=http://backendcontainer:8000
    #      - REACT_SERVICE_HOST=d_one_frontend
    networks:
      - d_one_network

  d_one_frontend:
    container_name: frontendcontainer
    build:
      context: ./dev_d_one/frontend
      dockerfile: ./Dockerfile
      args:
        BACKEND_ENDPOINT: $BACKEND_ENDPOINT
    ports:
      - "3000:3000"

    #      - BACKEND_ENDPOINT=http://backendcontainer:8000
    #      - BACKENDCONTAINER=http://backendcontainer:8000
    #       BACKEND_PORT: 8000
    #       BACKEND_HOST: backendcontainer
    #      - BACKEND_URL=http://backendcontainer:8000
    #    - BACKEND_URL=backendcontainer
    # links:
    #   - d_one_backend
    # depends_on:
    #   - d_one_backend
    networks:
      - d_one_network

  #  nginx:
  #    image: nginx:latest
  #    ports:
  #      - 80:80
  #    volumes:
  #      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
  #      - ./frontend/build:/var/www/frontend
  #    networks:
  #      - d_one_network
  nginx:
    container_name: nginx
    build: ./dev_d_one/nginx

    #    links:
    #        - backendcontainer
    #    environment:
    #      - FRONTEND_URL=frontendcontainer
    ports:
      - "80:80"
    networks:
      - d_one_network
networks:
  d_one_network:
    driver: bridge
