version: '3.8'

services:
  d_one_backend:
    environment:
      - FRONTEND_WEB_URL=http://d_one_frontend:3000
      - DJANGO_BACKEND_URL=http://d_one_backend:8000
    restart: unless-stopped
    build:
      context: ./dev_d_one/api_d_one
      dockerfile: ./Dockerfile
#    networks:
#      -
    ports:
      - '8000:8000'

#    links:
#      - d_one_frontend

  d_one_frontend:
    environment:
      - DJANGO_BACKEND_URL=http://d_one_backend:8000
    restart: unless-stopped
    build:
      context: ./dev_d_one/frontend
      dockerfile: ./Dockerfile
      args:
        base_url: http://localhost:8000
    ports:
      - '3000:3000'
    links:
      - d_one_backend


#https://github.com/jbenavidez/react-django-docker/blob/main/docker-compose-prod.yml