version: '3'

services:
  d_one_backend:
    build:
      context: .
      dockerfile: d_one_backend.Dockerfile
    ports:
      - '8000:8000'

  d_one_frontend:
    build:
      context: .
      dockerfile: d_one_frontend.Dockerfile
    ports:
      - '3000:3000'
