# Generated by Django 4.1.5 on 2023-01-23 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bodyPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('image', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='mainFeaturedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('image', models.TextField()),
                ('imageText', models.TextField()),
                ('linkText', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='newsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('image', models.TextField()),
            ],
        ),
    ]
