# Generated by Django 4.1.5 on 2023-02-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layout_api", "0003_testuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name="testUser",
        ),
    ]
