# Generated by Django 4.1.5 on 2023-03-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layout_api", "0004_email_delete_testuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="email",
            field=models.CharField(max_length=120, unique=b"I01\n"),
        ),
    ]
